### ISSUE TITLE
opensearch 支持

### ISSUE THREAD

**Issue by bGZo** [KoriIku/luxirty-search#14]
https://search.luxirty.com 无法被 Firefox 搜索引擎捕捉

![图片](https://github.com/user-attachments/assets/27562b95-1317-40af-a818-4841e8153b48)

原因是没有添加 opensearch 文件，你可能见过 FF 这样的提示:

![图片](https://github.com/user-attachments/assets/a880e9b1-889a-4876-8003-98f68cbccf40)

## 可能的解决措施

1. 动态捕获当前域名，自动生成opensearch 文件；
2. 直接为 https://search.luxirty.com 生成 opensearch 文件；

第 1 种方式时，我发现没有办法用相对路径指定URL

```
<Url type="text/html" method="get" template="/search?q={searchTerms}&amp;ref=opensearch"/>
```

所以，需要通过配置 Vue / Vercel 环境变量来动态填充，但在首次部署 Vercel 时，依然获得具体的域名来动态生成 opensearch 文件，仍然需要手动部署一次。

考虑当前项目还未引入 vercel 等环境变量，加上我也不太熟悉这块，所以想暂时用第 2 种方式为网站补充了 opensearch 文件。

> [!NOTE]
但是需要注意，如果是自托管 / 自部署，则需要修改 `opensearch.xml` 中的根域名，以保证最后添加到 FF 的搜索引擎的正确性。

1. PR 见 https://github.com/KoriIku/luxirty-search/pull/13
2. 文档见 https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by bGZo** [comment]
https://github.com/KoriIku/luxirty-search/pull/13 

PR 如上

**Comment by KoriIku** [comment]
已合并，感谢 PR~

**Comment by KoriIku** [comment]
啊，还需要在 Readme 中的 selfhost 部分添加相应提示，所以暂时保留一下以免我忘记。

**Comment by KoriIku** [comment]
已在 readme 添加相关提示。
