### ISSUE TITLE
使用后优化建议，搜索标题根据搜索内容调整（仿Google），便于多页签切换时定位页签

### ISSUE THREAD

**Issue by imyzt** [KoriIku/luxirty-search#15]
目前搜索结果页 `title` 是固定的 `Luxirty Search`，不便于当页签较多时被 Chrome 收缩只显示一个网页 icon 时定位页签。
举例：
<img width="368" alt="image" src="https://github.com/user-attachments/assets/ef0f3ed5-e271-4e0c-82c8-4dce9341b34b">

**Comment by KoriIku** [comment]
已合并，感谢 pr~
