### ISSUE TITLE
这个搜索似乎在国内环境用不了

### ISSUE THREAD

**Issue by huhaku** [KoriIku/luxirty-search#30]
看了下,有不少资源是直接使用google的,在国内有墙环境下是用不了的.有很多时候翻墙并不是那么方便
感觉是不是可以在服务器上做下反代去处理掉这些资源

**Comment by KoriIku** [comment]
可以考虑 whoogle 或者 searxng ，这些项目更符合需求。

**Comment by huhaku** [comment]
我之前用的就是searxng,感觉太重了,想找一个轻量化的替代方案.
不过没事,反代的问题我自己解决了,用国外的服务器反代样式有点错位,并且好像会自动跳到TW站去,不过问题不大,调一下就好
感谢你提供了一个那么好的前端

**Comment by KoriIku** [comment]
> 我之前用的就是searxng,感觉太重了,想找一个轻量化的替代方案. 不过没事,反代的问题我自己解决了,用国外的服务器反代样式有点错位,并且好像会自动跳到TW站去,不过问题不大,调一下就好 感谢你提供了一个那么好的前端

如果您有时间，是否可以在此分享您的解决方案，此 issue 已置顶，您的分享会对之后有相似问题的朋友有所帮助。

**Comment by huhaku** [comment]
将https://cse.google.com/cse.js?cx=%VITE_GOOGLE_CSE_CX%
替换为 /cse.js?cx=%VITE_GOOGLE_CSE_CX%

下面配置仅供参考
`server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
    
    location ^~ /cse.js {
        proxy_pass https://cse.google.com;
    
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/play {
        proxy_pass https://play.google.com;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/support {
        proxy_pass https://support.google.com;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/csqr {
        proxy_pass https://csqr-autopush.corp.google.com;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/csex {
        proxy_pass https://cse.google.com;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ads {
        proxy_pass https://www.adsensecustomsearchads.com;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/developers {
        proxy_pass https://developers.google.com;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/clients1 {
        proxy_pass https://clients1.google.com;
    
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 处理 /api 作为通用代理
    location /api {
        proxy_pass https://www.google.com;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    sub_filter '+zh_TW' '+zh_CN';
    sub_filter '=zh-TW' '=zh-CN';    
    # 处理输出中的 URL 替换
    sub_filter 'https://cse.google.com' '/api';
    sub_filter 'www.google.com' '/api';
    sub_filter '//play.google.com' '/api/play';
    sub_filter '//support.google.com' '/api/support';
    sub_filter '//csqr-autopush.corp.google.com' '/api/csqr';
    sub_filter '//cse.google.com' '/api/csex';
    sub_filter '//www.adsensecustomsearchads.com' '/api/ads';
    sub_filter '//developers.google.com' '/api/developers';

    # 处理搜索api
    sub_filter 'clients1.' '';
    sub_filter 'a.vs' '"/api/clients1"';

    proxy_set_header Accept-Encoding "";
    sub_filter_types text/css application/javascript;
    sub_filter_once off;
}
`

**Comment by zhyueyueniao** [comment]
这个是直接进docker里用你这个覆盖nginx配置就行了吗

**Comment by huhaku** [comment]
> 这个是直接进docker里用你这个覆盖nginx配置就行了吗

对,根据你自己的需求调整

**Comment by hzqim** [comment]
> > 这个是直接进docker里用你这个覆盖nginx配置就行了吗
> 
> 对, 不过不是直接覆盖,要根据你自己的需求调整

请问还需要修改哪些设置才可以过到目的？
我用上述nginx配置，除把 localhost 换成我的域名之后不知道还要设置什么。部署后页面发现没有搜索框，F12打开控制台，提示https://我的域名/cse.js?cx=%VITE_GOOGLE_CSE_CX% 404 not found.

**Comment by Hokori-null** [comment]
有个比较好的方法，首先得有一台能访问谷歌的服务器，然后将https://cse.google.com反带到服务器里，再到Luxirty Search的反带配置里用nginx的文本替换把https://cse.google.com替换成你的反带地址，亲测可用，下面是反带https://cse.google.com的配置
`location /cse/ {
        proxy_pass https://cse.google.com/;  # 注意末尾的 / 确保路径正确传递
        proxy_set_header Host cse.google.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # 解决 Google 可能的 CSP/重定向问题
        proxy_redirect ~^https://cse.google.com(.*) 自己的域名/cse$1;
        sub_filter_once off;
        sub_filter 'cse.google.com' '自己的域名/cse';
    }`
