### ISSUE TITLE
[bug]搜索结果网址显示问题

### ISSUE THREAD

**Issue by Crany-web** [KoriIku/luxirty-search#31]
<img width="496" alt="image" src="https://github.com/user-attachments/assets/69f834a1-862e-46f9-bcad-96cb61efb8cc">
<br>
搜索引擎的搜索结果没有网站的logo，这要分辨哪个结果就要依靠网站的title和title下面的网址，但是图中最上面的红框显示网址，中间的框显示的却是`网站title>metasploit-wiki`，页面下面的搜索结果也是一个网站显示完整URL，一个显示`网站title > 目录`，这种显示结果我觉得会给用户带来一些困惑或者不方便，希望能统一一下

**Comment by KoriIku** [comment]
已改为总是显示完整链接
